[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
jiao = { path = "..", features = ["web"] }
log = "0.4.16"
wasm-bindgen = "0.2.79"
wasm-logger = "0.2.0"
web-sys = "0.3.56"
yew = "0.19.3"
