[package]
name = "jiao"
version = "0.1.0"
edition = "2021"
description = "Cross platform 2D rendering engine"
homepage = "https://github.com/RustVis/jiao"
readme = "README.md"
license = "Apache-2.0"

[features]
default = ["web"]
cairo = ["cairo-rs"]
qt = ["qt_gui"]
skia = ["skia-safe"]
web = ["js-sys", "web-sys", "wasm-bindgen"]

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
lazy_static = "1.4.0"
log = "0.4.16"
cfg-if = "1.0.0"

[dependencies.cairo-rs]
version = "0.15.10"
optional = true
features = [
  "glib",
  "png",
  "svg",
  "pdf",
]

[dependencies.js-sys]
version = "0.3.57"
optional = true

[dependencies.qt_gui]
version = "0.5.0"
optional = true

[dependencies.skia-safe]
version = "0.49.0"
optional = true

[dependencies.web-sys]
version = "0.3.57"
optional = true
features = [
    "CanvasRenderingContext2d",
    "Document",
    "HtmlCanvasElement",
    "HtmlElement",
    "Path2d",
    "SvgElement",
    "Window",
]

[dependencies.wasm-bindgen]
version = "0.2.80"
optional = true
features = ["serde-serialize"]

[dev-dependencies]
serde_json = "1.0.79"
