
[workspace]
members = [
  "crates/jiao",
  "crates/jiao-cairo",
  "crates/jiao-qt",
  #"crates/jiao-shapes",
  "crates/jiao-skia",
  #"crates/jiao-web",
]

exclude = [
  "examples/*",
  "tools/*",
]

resolver = "2"
