[package]
name = "jiao"
version = "0.1.0"
edition = "2021"
description = "Cross platform 2D rendering engine"

[features]
default = ["web"]
gtk = ["cairo-rs"]
qt = ["qt_gui"]
web = ["web-sys", "wasm-bindgen"]

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }

[dependencies.qt_gui]
version = "0.5.0"
optional = true

[dependencies.cairo-rs]
version = "0.15.6"
optional = true

[dependencies.web-sys]
version = "0.3.56"
optional = true
features = ["CanvasRenderingContext2d"]

[dependencies.wasm-bindgen]
version = "0.2.79"
optional = true
features = ["serde-serialize"]

[dev-dependencies]
serde_json = "1.0.79"
