[package]
name = "jiao"
version = "0.1.0"
edition = "2021"

[features]
default = []
gtk = ["cairo-rs"]
qt = ["qt_gui"]
wasm = ["web-sys", "wasm-bindgen"]

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }

[dependencies.qt_gui]
version = "0.5.0"
optional = true

[dependencies.cairo-rs]
version = "0.15.1"
optional = true

[dependencies.web-sys]
version = "0.3.56"
optional = true
features = ["CanvasRenderingContext2d"]

[dependencies.wasm-bindgen]
version = "0.2.79"
optional = true
features = ["serde-serialize"]
