[package]
name = "jiao-cairo"
version = "0.1.0"
edition = "2021"

[dependencies]
jiao = { path="../jiao" }
log = "0.4.17"

[dependencies.cairo-rs]
version = "0.16.7"
features = ["glib", "png", "svg", "pdf"]
