[package]
name = "jiao-cairo"
version = "0.2.1"
edition = "2021"

[dependencies]
cairo-rs = { version="0.16.7", features=["glib", "png", "svg", "pdf"] }
jiao = { path="../jiao", version="0.2.1" }
log = "0.4.17"
