[package]
name = "skia_images"
version = "0.1.0"
edition = "2021"

[dependencies]
jiao-shapes = { path = "../../crates/jiao-shapes", features = ["skia"] }
jiao-skia = { path = "../../crates/jiao-skia" }
paint-shapes = { path = "../paint-shapes", features = ["skia"] }
skia-safe = "0.58.0"
