[package]
name = "skia_images"
version = "0.1.0"
edition = "2021"

[dependencies]
jiao = { path = "../..", features = ["skia"] }
paint_shapes = { path = "../paint_shapes", features = ["skia"] }
skia-safe = "0.58.0"
