[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
jiao = { path = "../..", features = ["web"] }
log = "0.4.17"
wasm-bindgen = "0.2.84"
wasm-logger = "0.2.0"
web-sys = "0.3.61"
yew = { version = "0.20.0", features = ["csr"] }
