[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
jiao = { path = "../..", default-features=false, features = ["web"] }
log = "0.4.17"
wasm-bindgen = "0.2.80"
wasm-logger = "0.2.0"
web-sys = "0.3.57"
yew = "0.19.3"
