[package]
name = "qt_image"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
cpp_core = "0.6.0"
jiao-shapes = { path = "../../crates/jiao-shapes", features = ["qt"] }
paint-shapes = { path = "../paint-shapes", features = ["qt"] }
qt_core = "0.5.0"
qt_gui = "0.5.0"
