[package]
name = "jiao_gtk"
version = "0.1.0"
edition = "2021"

[dependencies]
jiao = { path="../jiao" }

[dependencies.cairo-rs]
version = "0.16.7"
optional = true
features = [
  "glib",
  "png",
  "svg",
  "pdf",
]
