[package]
name = "paint_shapes"
version = "0.1.0"
edition = "2021"

[features]
cairo = ["jiao/cairo"]
qt = ["jiao/qt"]
skia = ["jiao/skia"]
web = ["jiao/web"]

[dependencies]
jiao = { path = "../..", default-features = false }
