name: ci
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  schedule:
  - cron: '00 01 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
        - pinned
        - stable
        - beta
        - nightly
        include:
        - build: pinned
          os: ubuntu-18.04
          rust: 1.46.0
        - build: stable
          os: ubuntu-18.04
          rust: stable
        - build: beta
          os: ubuntu-18.04
          rust: beta
        - build: nightly
          os: ubuntu-18.04
          rust: nightly
    steps:
    - uses: actions/checkout@v2
    - run: env
    - run: ls -l
    - run: cargo build --verbose
    - run: cargo doc --verbose
    - run: cargo test --verbose
